name: daily_report
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  common_utils: ^2.1.0
  dio: ^5.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  get: ^4.6.5
  get_storage: ^2.1.1
  responsive_framework: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
